/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_tk_tanguy_droidsshd_system_NativeTask
#define _Included_tk_tanguy_droidsshd_system_NativeTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tk_tanguy_droidsshd_system_NativeTask
 * Method:    runCommand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tk_tanguy_droidsshd_system_NativeTask_runCommand
  (JNIEnv *, jclass, jstring);

/*
 * Class:     tk_tanguy_droidsshd_system_NativeTask
 * Method:    chmod
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_tk_tanguy_droidsshd_system_NativeTask_chmod
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     tk_tanguy_droidsshd_system_NativeTask
 * Method:    symlink
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tk_tanguy_droidsshd_system_NativeTask_symlink
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
